local addonName, ns = ...

ns.ReleaseNotes = {
    notes = {
        ["v2.0.3"] = {
            "|cffff2020[Hotfix 2.0.3a]|r Fixed a Lua error (nil value) occurring when entering Shroud mode immediately after addon load.",
            "|cff00d1ff[New]|r Added |cffffd100/veil shroud|r — a |cffffd100Debug Mode|r command that simulates a real Shroud countdown using your configured channels, messages, and error checks, identical to an actual cast. Default duration is 15 seconds.",
            "|cff00ff00[Improved]|r Debug Mode structure refined via |cffffd100/veil debug|r, isolating technical commands to prevent accidental use during normal gameplay.",
            "|cff00ff00[Improved]|r The |cffffd100Test Message|r button in Settings now performs a fixed 5-second local-only simulation, safe to use at any time without broadcasting to chat.",
            "|cff00ff00[Improved]|r Shroud error messages (such as 'No Valid Channel' or 'Not in Instance') are now strictly suppressed after the first occurrence per cast, preventing repeated spam.",
            "|cff00ff00[Fixed]|r Fixed an issue where editing configuration options had no effect, preventing changes from properly updating their behavior.",
        },
        ["v2.0.2"] = {
            "|cff00d1ff[New]|r Added advanced version compatibility system with automatic config recovery for compatible versions.",
            "|cff00d1ff[New]|r Added update notification popups when a different but compatible addon version is detected.",
            "|cff00d1ff[New]|r Added recommended update confirmation popup when version mismatch occurs.",
            "|cff00d1ff[New]|r Reintroduced |cffffd100SAY|r and |cffffd100YELL|r channels with proper instance restrictions.",
            "|cff00d1ff[New]|r Added |cffffd100Debug Mode|r via |cffffd100/veil debug|r with runtime diagnostics for message conditions.",
            "|cff00ff00[Improved]|r Fully redesigned Shroud message system using a new chat handling framework.",
            "|cff00ff00[Improved]|r Integrated |cffffd100ChatThrottleLib|r |cff808080(by Nevcairiel)|r for safe and throttled chat communication.",
            "|cff00ff00[Improved]|r Optimized Shroud countdown messages for precise timing and consistency.",
            "|cff00ff00[Improved]|r Reworked |cffffd100Instance Only|r option to support the new system.",
            "|cffffd100[Changed]|r Reworked channel condition system to accurately detect party, raid, pets and other group entities.",
            "|cffffff00[UI]|r Test Message button now sends real chat messages for accurate preview behavior.",
        },
        ["v2.0.1"] = {
            "|cff00d1ff[New]|r Added login Welcome and Update notification messages.",
            "|cff00d1ff[New]|r Automatic |cffffd100/reload|r prompt when handling incompatible configurations.",
            "|cff00ff00[Improved]|r Enhanced addon versioning and compatibility check system.",
            "|cff00ff00[Fixed]|r Adjusted Non-Lethal Poison icon anchoring relative to default text.",
        },
        ["v2.0.0"] = {
            "|cff00d1ff[New]|r Redesigned configuration interface using |cffffd100LibEQOL|r |cff808080(by R41Z0R)|r.",
            "|cff00d1ff[New]|r Integrated Profile System with Import/Export functionality.",
            "|cff00d1ff[New]|r Added a 'Test Message' button to preview Shroud alerts.",
            "|cff00d1ff[New]|r Added 2 fully configurable fallback channels for Shroud (automatically ignores group channels when solo).",
            "|cff00d1ff[New]|r Version-check system implemented to prevent config corruption.",
            "|cff00ff00[Improved]|r Enhanced Shroud countdown tracking for precision.",
            "|cff00ff00[Refactored]|r The instance-based detection system has been completely rewritten for better reliability.",
            "|cff00ff00[Fixed]|r Resolved errors when using Shroud of Concealment outside of instances.",
            "|cff00ff00[Fixed]|r Shroud start and end messages now broadcast correctly.",
            "|cff00ff00[Fixed]|r Custom Shroud messages are now properly saved between sessions.",
            "|cffffd100[Changed]|r Shroud time variable changed from |cffffd100%t|r to |cffffd100%time|r to avoid conflicts.",
            "|cffffd100[Localization]|r Full translation support for all official WoW languages.",
            "|cffffff00[UI]|r Moved the Reset button to the native 'Defaults' button in the settings menu.",
            "|cffff2020[Removed]|r Shadow Dance support due to stability issues and limited utility.",
            "|cffff2020[Removed]|r SAY and YELL options removed due to Blizzard limitations on scripted messages in these channels.",
        },
        ["v1.0.1"] = {
            "|cff00d1ff[New]|r Added |cffffd100Rogue Poison Tracker|r module with visual alerts.",
            "|cff00d1ff[New]|r Support for |cffffd100Addon Compartment|r (Minimap button integration).",
            "|cff00ff00[Improved]|r Renamed addon to better reflect core features and future updates.",
            "|cff00ff00[Improved]|r Enhanced icon anchoring and dynamic scaling system.",
            "|cff00ff00[Improved]|r Optimized instance and combat state detection filters.",
            "|cffffd100[Visual]|r Added high-fidelity text animations and transition effects.",
            "|cffffff00[Misc]|r Updated default configuration values and localization files.",
        },
        ["v1.0.0"] = {
            "|cffffff00[Initial]|r First stable public release.",
            "|cff00d1ff[Core]|r Full support for |cffffd100Stealth|r and |cffffd100Shadow Dance|r visual states.",
            "|cff00d1ff[Core]|r Integrated |cffffd100Self-Highlight|r visibility features for character tracking.",
            "|cff00d1ff[Core]|r Specialized chat broadcast system for Shroud of Concealment.",
            "|cffffd100[Visual]|r Extensive styling options and visual effect customization.",
        },
    }
}