local addonName, ns = ...

ns.ReleaseNotes = {
    notes = {
        ["v2.2.1"] = {
            "|cff00ff00[Fixed]|r Shroud now only tracks your own aura to avoid spam. |cff808080(Reported by xrandomassassin)|r",
        },
        ["v2.2.0"] = {
            "|cff00d1ff[New]|r Added full multiclass support with shared core systems.",
            "|cff00d1ff[New]|r Added generic |cffffd100Stealth State|r system available for all classes.",
            "|cff00d1ff[New]|r Added Hunter support with |cffffd100Camouflage|r tracking and |cffffd100Misdirection|r automation.",
            "|cff00d1ff[New]|r Highlights are now a standalone system with support for combat, instance, and more conditions.",
            "|cff00d1ff[New]|r Added conditional instance exclusion system for dungeons and raids.",
            "|cff00ff00[Improved]|r Stealth detection can now use state-based logic instead of aura-only tracking.",
            "|cff00ff00[Improved]|r Poison tracking now has independent configuration per poison type.",
            "|cff00ff00[Refactored]|r Core rewritten to support modular multiclass architecture.",
            "|cffffd100[Changed]|r Highlights are no longer tied directly to Stealth and now operate independently.",
            "|cffff2020[Removed]|r Temporarily removed animation system due to stability issues.",
            "|cffffff00[Misc]|r Added option to delete character profiles to prevent duplication issues.",
            "|cffffff00[Misc]|r Updated addon license with additional usage and distribution restrictions.",
        },
        ["v2.1.2"] = {
            "|cff00d1ff[New]|r Valeera Sanguinar now supported as a Delve Companion for Tricks.",
            "|cff00d1ff[New]|r Added dedicated zhTW localization file.",
            "|cff00d1ff[New]|r Added Factory Reset button with confirmation in Profile tab.",
            "|cff00ff00[Improved]|r Complete visual redesign: colors, icons, and banner updated.",
            "|cff00ff00[Improved]|r Improved restrictions for non-Rogues to prevent unintended usage.",
            "|cff00ff00[Improved]|r Stealth now uses aura-based detection.",
            "|cff00ff00[Fixed]|r Stealth highlights no longer persist after logout while stealthed.",
            "|cffffd100[Localization]|r Full overhaul with official terms and improved translations.",
        },
        ["v2.1.1"] = {
            "|cff00d1ff[New]|r Replaced Tricks checkbox with dedicated Activate/Deactivate buttons.",
            "|cff00ff00[Fixed]|r Adjusted chat message priority for better logging order.",
        },
        ["v2.1.0"] = {
            "|cff00d1ff[New]|r Added the Tricks system: smart macro management, mode switching, and custom targeting.",
            "|cff00d1ff[New]|r Added |cffffd100/veil tricks|r commands to easily manage targeting modes.",
            "|cff00d1ff[New]|r Added |cffffd100/veil help|r command.",
            "|cff00d1ff[New]|r Added feedback for unknown commands and combat-restricted actions.",
            "|cff00ff00[Fixed]|r Properly hidden class categories for non-Rogue players.",
            "|cff00ff00[Fixed]|r Resolved spell detection and settings registration issues.",
            "|cffffd100[Localization]|r Complete update for all 9 supported languages.",
            "|cffffff00[Misc]|r Bug credits added. Apologies for the delay — future reports will be properly acknowledged!",
        },
        ["v2.0.3"] = {
            "|cffff2020[Hotfix 2.0.3a]|r Fixed a Lua error (nil) after load. |cff808080(Reported by rpearso8)|r",
            "|cff00d1ff[New]|r Added |cffffd100/veil shroud|r — simulates real Shroud countdown with full logic and error checks.",
            "|cff00ff00[Improved]|r Debug Mode refined via |cffffd100/veil debug|r to isolate technical commands.",
            "|cff00ff00[Improved]|r Test button now performs a quick 5s local simulation, safe for solo use.",
            "|cff00ff00[Improved]|r Shroud errors are suppressed after first occurrence to prevent spam.",
            "|cff00ff00[Fixed]|r Fixed config changes not updating behavior correctly.",
        },
        ["v2.0.2"] = {
            "|cff00d1ff[New]|r Added version compatibility system with automatic recovery.",
            "|cff00d1ff[New]|r Added update notification popups for compatible version changes.",
            "|cff00d1ff[New]|r Added confirmation popup for recommended updates on version mismatch.",
            "|cff00d1ff[New]|r Reintroduced |cffffd100SAY|r and |cffffd100YELL|r with instance restrictions.",
            "|cff00d1ff[New]|r Added |cffffd100Debug Mode|r with runtime diagnostics for messages.",
            "|cff00ff00[Improved]|r Redesigned Shroud message system using a new chat framework.",
            "|cff00ff00[Improved]|r Integrated |cffffd100ChatThrottleLib|r for safe messages. |cff808080(by NevCairiel and Forge_User_96189362)|r",
            "|cff00ff00[Improved]|r Optimized Shroud countdown messages for precise timing.",
            "|cff00ff00[Improved]|r Reworked |cffffd100Instance Only|r option to support the new system.",
            "|cffffd100[Changed]|r Correctly detect party, raid, pets and other entities.",
            "|cffffff00[UI]|r Test button sends real chat messages for accurate behavior preview.",
        },
        ["v2.0.1"] = {
            "|cff00d1ff[New]|r Added login Welcome and Update notification messages.",
            "|cff00d1ff[New]|r Automatic reload prompt when handling incompatible configs.",
            "|cff00ff00[Improved]|r Enhanced versioning and compatibility check system.",
            "|cff00ff00[Fixed]|r Adjusted Non-Lethal Poison icon anchoring.",
        },
        ["v2.0.0"] = {
            "|cff00d1ff[New]|r Redesigned interface using |cffffd100LibEQOL|r |cff808080(by R41Z0R)|r.",
            "|cff00d1ff[New]|r Profile System with Import/Export functionality.",
            "|cff00d1ff[New]|r Added a 'Test Message' button to preview Shroud alerts.",
            "|cff00d1ff[New]|r 2 fallback channels (auto-ignores group channels when solo).",
            "|cff00d1ff[New]|r Version-check system to prevent config corruption.",
            "|cff00ff00[Improved]|r Enhanced Shroud countdown tracking for precision.",
            "|cff00ff00[Refactored]|r Completely rewritten instance detection for better reliability.",
            "|cff00ff00[Fixed]|r Fixed Shroud errors outside instances. |cff808080(Reported by rpearso8)|r",
            "|cff00ff00[Fixed]|r Text disappearing after reload. |cff808080(Reported by rpearso8 & WorryAboutStuff)|r",
            "|cff00ff00[Fixed]|r Shroud start and end messages now broadcast correctly.",
            "|cff00ff00[Fixed]|r Custom Shroud messages are properly saved.",
            "|cffffd100[Changed]|r Shroud time variable changed from |cffffd100%t|r to |cffffd100%time|r.",
            "|cffffd100[Localization]|r Full translation support for all official languages.",
            "|cffffff00[UI]|r Moved Reset to native 'Defaults' button in settings.",
            "|cffff2020[Removed]|r Shadow Dance support due to stability issues.",
            "|cffff2020[Removed]|r SAY/YELL removed due to Blizzard limitations.",
        },
        ["v1.0.1"] = {
            "|cff00d1ff[New]|r Added |cffffd100Poison Tracker|r with visual alerts.",
            "|cff00d1ff[New]|r Support for |cffffd100Addon Compartment|r.",
            "|cff00ff00[Improved]|r Renamed addon to better reflect core features.",
            "|cff00ff00[Improved]|r Enhanced icon anchoring and dynamic scaling.",
            "|cff00ff00[Improved]|r Optimized instance and combat state detection.",
            "|cffffd100[Visual]|r Added high-fidelity text animations.",
            "|cffffff00[Misc]|r Updated default configuration and locales.",
        },
        ["v1.0.0"] = {
            "|cffffff00[Initial]|r First stable public release.",
            "|cff00d1ff[Core]|r Support for |cffffd100Stealth|r and |cffffd100Shadow Dance|r states.",
            "|cff00d1ff[Core]|r Integrated |cffffd100Self-Highlight|r for character tracking.",
            "|cff00d1ff[Core]|r Specialized chat broadcast system for Shroud.",
            "|cffffd100[Visual]|r Extensive styling and visual customization.",
        },
    }
}