local addonName, ns = ...

ns.Defaults = {
    stealthEnabled = true,
    stealthOnlyInstances = false,
    enableText = true,
    customText = ns.L.DefaultMessage,
    textColor = {r = 0.64, g = 0.38, b = 0.89},
    textAlpha = 1,
    textX = 0,
    textY = 185,
    textSize = 32,
    textAnim = "NONE",
    textAnimSpeed = 1,
    enableIcon = false,
    iconSize = 64,
    iconAlpha = 1,
    iconAnchorToText = false,
    iconAnchorPoint = "LEFT",
    iconX = 0,
    iconY = 400,
    enableScreenColor = true,
    screenColor = {r = 0.64, g = 0.38, b = 0.89},
    screenAlpha = 0.1,
    screenStrata = "BACKGROUND",
    enableVignette = true,
    vignetteSize = 250,
    vignetteAlpha = 0.6,
    vignetteStrata = "BACKGROUND",
    enableHighlight = true,
    highlightType = 2,

    sdEnabled = false,
    sdOnlyCombat = false,
    sdOnlyInstances = false,
    sdEnableText = false,
    sdCustomText = ns.L.ShadowDanceMessage,
    sdTextColor = {r = 0.64, g = 0.38, b = 0.89},
    sdTextAlpha = 0.8,
    sdTextX = 0,
    sdTextY = 185,
    sdTextSize = 32,
    sdTextAnim = "NONE",
    sdTextAnimSpeed = 1,
    sdEnableIcon = false,
    sdIconSize = 36,
    sdIconAlpha = 0.8,
    sdIconAnchorToText = true,
    sdIconAnchorPoint = "LEFT",
    sdIconX = 10,
    sdIconY = 0,
    sdEnableScreenColor = true,
    sdScreenColor = {r = 0.64, g = 0.38, b = 0.89},
    sdScreenAlpha = 0.06,
    sdScreenStrata = "BACKGROUND",
    sdEnableVignette = true,
    sdVignetteSize = 250,
    sdVignetteAlpha = 0.6,
    sdVignetteStrata = "BACKGROUND",
    sdEnableHighlight = true,
    sdHighlightType = 2,

    shroudCountdown = true,
    shroudOnlyInstances = true,
    shroudChannel = "PARTY",
    shroudMessage = "Teste: %t",
    shroudInterval = false,
    shroudStartMsg = "",
    shroudEndMsg = "",

    poisonTrackerEnabled = true,
    poisonOnlyCombat = true,
    poisonOnlyInstances = false,
    
    poisonLethalEnabled = true,
    poisonLethalEnableText = true,
    poisonLethalCustomText = ns.L.LethalPoisonMissing,
    poisonLethalTextColor = {r = 1, g = 0.2, b = 0.2},
    poisonLethalTextAlpha = 1,
    poisonLethalTextX = 0,
    poisonLethalTextY = 300,
    poisonLethalTextSize = 28,
    poisonLethalTextAnim = "NONE",
    poisonLethalTextAnimSpeed = 1,
    poisonLethalEnableIcon = true,
    poisonLethalIconSpellId = 315584,
    poisonLethalIconTexture = "Interface\\Icons\\Ability_Poisons",
    poisonLethalIconSize = 36,
    poisonLethalIconAlpha = 1,
    poisonLethalIconAnchorToText = true,
    poisonLethalIconAnchorPoint = "LEFT",
    poisonLethalIconX = 10,
    poisonLethalIconY = 0,
    poisonLethalEnableSound = true,
    poisonLethalSoundKit = (SOUNDKIT and SOUNDKIT.RAID_WARNING) or 8959,

    poisonNonLethalEnabled = true,
    poisonNonLethalEnableText = true,
    poisonNonLethalCustomText = ns.L.NonLethalPoisonMissing,
    poisonNonLethalTextColor = {r = 1, g = 0.6, b = 0.2},
    poisonNonLethalTextAlpha = 1,
    poisonNonLethalTextX = 0,
    poisonNonLethalTextY = 260,
    poisonNonLethalTextSize = 28,
    poisonNonLethalTextAnim = "NONE",
    poisonNonLethalTextAnimSpeed = 1,
    poisonNonLethalEnableIcon = true,
    poisonNonLethalIconSpellId = 3408,
    poisonNonLethalIconTexture = "Interface\\Icons\\Ability_PoisonSting",
    poisonNonLethalIconSize = 36,
    poisonNonLethalIconAlpha = 1,
    poisonNonLethalIconAnchorToText = true,
    poisonNonLethalIconAnchorPoint = "LEFT",
    poisonNonLethalIconX = 10,
    poisonNonLethalIconY = 0,
    poisonNonLethalEnableSound = true,
    poisonNonLethalSoundKit = (SOUNDKIT and SOUNDKIT.RAID_WARNING) or 8959,
}

function ns.CopyDefaults(src, dst)
    for k, v in pairs(src) do
        if type(v) == "table" then
            dst[k] = dst[k] or {}
            ns.CopyDefaults(v, dst[k])
        elseif dst[k] == nil then
            dst[k] = v
        end
    end
end
